# download command/URL (optional)
# download: 

# train and val data as 
# 1) directory: path/images/,
# 2) file: path/images.txt, or 
# 3) list: [path1/images/, path2/images/]

metadata:
  # Basic attribute
  directory: E:/dataset/

  # Debug attribute(s)
  load: True

dataset:
  # Basic attribute
  directory: E:/dataset/

video:
  # Debug attributes
  display: True
  write: True

  # Basic attributes
  resize: True 
  width: 640
  height: 360
  depth: 3
