mode: pretrain

data:
  visualize: False
  directory: ../data/mask/
  output_directory: "../data/maskface/"

loader:
  batch_size: 2

model:
  directory: "pretrain/"
  epochs: 25
  num_classes: 2

  lr: 0.0001

